### ISSUE TITLE
[BUG & FEATURE] 프로필 수정

### ISSUE THREAD

**Issue by hyojine** [onestone2team/StoneCoffee_Frontend#101]
## 📍BEFORE
![image](https://user-images.githubusercontent.com/113072934/209075242-fd962efa-f5b0-42a8-be2e-3f1adc19de98.png)

## 📍TODOLIST
- [x] 핸드폰 번호 작성시 - 자동 적용 미적용 js
- [x] 프로필 창과 프로필 수정창이 별도로 있는 게 좋을듯?
- [x] 돌아가기 부분 x표시 없애기
- [x] 주소랑 핸드폰번호 null → ‘ ’ 변경
- [ ] 탈퇴하기 기능 추가

**Comment by JoonPyoJang** [comment]
탈퇴하기 기능 보류
