### ISSUE TITLE
[BUG & FEATURE] 네비바

### ISSUE THREAD

**Issue by hyojine** [onestone2team/StoneCoffee_Frontend#104]
## 📍BEFORE
![image](https://user-images.githubusercontent.com/113072934/209071579-99aa4d8c-0ddb-4cd0-806b-2c9e17b232d0.png)
## 📍TODOLIST
- [x] 000님(링크) → 000님 안녕하세요! 문구 옆에 마이페이지(링크) 추가
- [ ] 고객센터 추가

**Comment by JoonPyoJang** [comment]
![image](https://user-images.githubusercontent.com/113072934/209071579-99aa4d8c-0ddb-4cd0-806b-2c9e17b232d0.png)

**Comment by JoonPyoJang** [comment]
![image](https://user-images.githubusercontent.com/113072934/209074684-aa6caf11-9aea-401d-bfc1-bda72c0b8980.png)
