### ISSUE TITLE
fix & update: 네비게이션바 수정

### ISSUE THREAD

**Issue by hyojine** [onestone2team/StoneCoffee_Frontend#37]
- 상품 등록 버튼 - 관리자일 때만 보이게
- 모바일에서 사라짐
- 000님 반갑습니다! 이런 문구 들어가는 부분 추가 **헤더 수정**
- 관리자 페이지/마이페이지로 진입가능한 버튼 추가

**Comment by JoonPyoJang** [comment]
수정 후
![image](https://user-images.githubusercontent.com/113072934/208411426-b8a48768-90b3-43a5-b872-8644c8944c4c.png)
