### ISSUE TITLE
fix & update: 카테고리 바 추가

### ISSUE THREAD

**Issue by hyojine** [onestone2team/StoneCoffee_Frontend#38]
네비바에서 관리자/마이페이지 버튼 눌렀을 때
각 페이지마다 카테고리바 하단에 뜨도록
- 관리자 카테고리 바
- 마이페이지 카테고리 바

**Comment by JoonPyoJang** [comment]
![image](https://user-images.githubusercontent.com/113072934/208306086-8e6a79f9-bf2a-49d0-9b65-b7414439fcbf.png)

![image](https://user-images.githubusercontent.com/113072934/208306114-911cb30c-2197-4797-ba12-674520a01594.png)
