### ISSUE TITLE
update: 카테고리별 페이지

### ISSUE THREAD

**Issue by hyojine** [onestone2team/StoneCoffee_Frontend#43]
- 페이지네이션 -> 페이지 번호 나타나게 변경

**Comment by JoonPyoJang** [comment]
할거임

**Comment by JoonPyoJang** [comment]
기존
![image](https://user-images.githubusercontent.com/113072934/208404639-7f3e2cc0-5023-4d23-b5f1-76b15d06c8b2.png)

축소시
![image](https://user-images.githubusercontent.com/113072934/208404722-2ae8d76e-cc31-4795-b090-d80bb8e9d8e7.png)

**Comment by JoonPyoJang** [comment]
확대
![image](https://user-images.githubusercontent.com/113072934/208520661-770aaa87-3939-4237-88e7-14282dfacd57.png)

축소 시
![image](https://user-images.githubusercontent.com/113072934/208520917-01b673f5-4f19-4db3-8808-4da1b7d14911.png)
