### ISSUE TITLE
[BUG & FEATURE] 상세 페이지

### ISSUE THREAD

**Issue by hyojine** [onestone2team/StoneCoffee_Frontend#45]
## 📍TODOLIST
- [ ] 굿즈/커피용품 상품 설명부분 안채우면 짜부러지는거 어떻게 하기
- [ ] 상품 추천하는 부분 크기 조정 필요(넘어가는 걸로 수정)
- [ ] 굿즈 / 커피용품 상세 페이지에서는 해당 카테고리 상품들을 아래 추천 목록에 띄우기
- [ ] 댓글 등록/좋아요하는 부분 비동기식으로 수정- 백엔드 수정?
- [ ] 1g 옵션 없애기(안보이게만 바꾸기?)-주문목록/결제페이지 등에서 다 보임

**Comment by hyeoneeeeee** [comment]
제가 할게요
