### ISSUE TITLE
[BUG & FEATURE] 장바구니 페이지

### ISSUE THREAD

**Issue by hyojine** [onestone2team/StoneCoffee_Frontend#47]
## 📍TODOLIST
- [x] 상품 사진 비율로 바꾸기(미니멈을 더 줄여야함)
- [x] 글자도 미니멈 사이즈 줄 수 있는지 확인
- [x] 1g 기본값 옵션 빼기/원두일때만 주기

**Comment by hyeoneeeeee** [comment]
제가 할게요
