### ISSUE TITLE
[BUG & FEATURE] 주문목록 페이지

### ISSUE THREAD

**Issue by hyojine** [onestone2team/StoneCoffee_Frontend#49]
## 📍TODOLIST
- [x] 주문 목록 박스 크기 키우기(상품이 3~4개 정도 보이게!)
- [ ] 정렬 최신 순으로 바꾸기
- [x] 1g 옵션 없앤 거 확인

**Comment by JoonPyoJang** [comment]
수정 전
![image](https://user-images.githubusercontent.com/113072934/208354593-f9234feb-17ae-47d0-9d1b-4f56fed5bcda.png)

**Comment by JoonPyoJang** [comment]
UI 변경
![image](https://user-images.githubusercontent.com/113072934/208380939-a6f84b51-bef6-48bf-ae45-c6434096290c.png)
작아졌을때
![image](https://user-images.githubusercontent.com/113072934/208381090-524a6acb-438d-4807-ad40-29b8f1ff8750.png)

용량 1g 일때 글자 제거
![image](https://user-images.githubusercontent.com/113072934/208380779-f92e287c-1f57-40f3-ad66-80ff7ee2d2bb.png)
