### ISSUE TITLE
[BUG & FEATURE] 카테고리 페이지

### ISSUE THREAD

**Issue by hyojine** [onestone2team/StoneCoffee_Frontend#96]
## 📍BEFORE
![image](https://user-images.githubusercontent.com/113072934/209128683-c7fc852f-ff2a-4ee6-b81d-a4db8914b9c4.png)

![image](https://user-images.githubusercontent.com/113072934/209128617-294acb70-5f64-4430-b1d8-f8be4450cd81.png)

## 📍TODOLIST
- [x] 페이지네이션 수정
- [x] 각 항목별 오름차순/내림차순 정렬 명시

**Comment by JoonPyoJang** [comment]
페이지네이션
![image](https://user-images.githubusercontent.com/113072934/209166444-01c0e814-e952-4241-b23c-e1c47102b479.png)
내림차순 오름차순
![image](https://user-images.githubusercontent.com/113072934/209166618-44f97029-327b-4a06-b70c-a6b30312fa51.png)
