### ISSUE TITLE
[BUG & FEATURE] 상품 상세 페이지

### ISSUE THREAD

**Issue by hyojine** [onestone2team/StoneCoffee_Frontend#97]
## 📍TODOLIST
- [x] 기본중량 100g 옵션 생성
- [x] 좋아요 alert 없애기
- [x] 평점 이미지 별 > 원두 통일
- [x] 평점 선택 라디오 버튼으로 변경?
- [x] 주문한 사람만 댓글 쓸 수 있게
- [x] 댓글수정시 사진만 수정할 수가 없음(확장자 문제→ jpeg, jpg, png 만 가능하다고 명시해놓을 것)
- [ ] 댓글 목록형식으로 수정
- [x] 가격 형식 지킬 것

**Comment by hyeoneeeeee** [comment]
제가 할게요
