### ISSUE TITLE
[BUG & FEATURE] 장바구니

### ISSUE THREAD

**Issue by hyojine** [onestone2team/StoneCoffee_Frontend#99]
## 📍TODOLIST
- [x] 모바일에서 사진이 너무 큼
- [x] 장바구니에서 삭제시 알럿 창 필요
- [x] 가격 형식 지킬 것

**Comment by Beam-ki** [comment]
세개다 수정은했는데 장바구니에서 물건을 뺏을때 가격변동이 있습니다.
뺀물건만큼 가격이빠지는게아니라 백단위로 빠져요.
